In [6]:
import numpy as np
chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1  
chessboard[::2, 1::2] = 1  

print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
matrix = np.tile(np.arange(5), (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [8]:
random_array = np.random.randint(0,10, (3, 3, 3))

print(random_array)

[[[6 4 5]
  [1 0 9]
  [7 4 8]]

 [[2 2 7]
  [8 7 0]
  [2 6 3]]

 [[0 4 8]
  [0 5 9]
  [3 2 2]]]


In [9]:
array2 = np.zeros((5, 5), dtype=int)
array2[0,0:5] = 1
array2[0:5,0] = 1
array2[4,0:5] = 1
array2[0:5,4] = 1
print(array2) 

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [10]:


array = np.random.randint(0, 100, 10)
print("Исходный массив:", " ".join(map(str, array)))

sorted_array = np.sort(array)[::-1]
print("Отсортированный массив:", " ".join(map(str, sorted_array)))


Исходный массив: 60 59 33 45 79 87 62 40 65 81
Отсортированный массив: 87 81 79 65 62 60 59 45 40 33


In [11]:
matrix = np.random.randint(0, 10, (4, 5))

print("Матрица:\n", matrix)


print("Форма матрицы:", matrix.shape)
print("Размер матрицы:", matrix.size)
print("Размерность матрицы:", matrix.ndim)


Матрица:
 [[2 4 9 8 5]
 [2 8 8 3 7]
 [2 9 4 7 1]
 [9 0 8 7 9]]
Форма матрицы: (4, 5)
Размер матрицы: 20
Размерность матрицы: 2


In [12]:
import pandas as pd
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

# Вычисляем Евклидово расстояние вручную
distance = np.sqrt(((a - b) ** 2).sum())

print("Евклидово расстояние:", distance)

Евклидово расстояние: 5.196152422706632


In [13]:
usrl = 'D:/GitHub/СИИБД/airlines.csv'
df = pd.read_csv(usrl)
df.head(5)



Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0

In [14]:
df.tail(3)


Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

In [15]:
df.shape


(539383, 8)

In [16]:
df.describe()

Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000   
mean     2427.928630       3.929668     802.728963     132.202007   
std      2067.429837       1.914664     278.045911      70.117016   
min         1.000000       1.000000      10.000000       0.000000   
25%       712.000000       2.000000     565.000000      81.000000   
50%      1809.000000       4.000000     795.000000     115.000000   
75%      3745.000000       5.000000    1035.000000     162.000000   
max      7814.000000       7.000000    1439.000000     655.000000   

               Delay  
count  539383.000000  
mean        0.445442  
std         0.497015  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [17]:
df.iloc[8:245]

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
8        DL    2606         SFO       MSP          3    35     216      1
9        AA    2538         LAS       ORD          3    40     200      1
10       CO     223         ANC       SEA          3    49     201      1
11       DL    1646         PHX       ATL          3    50     212      1
12       DL    2055         SLC       ATL          3    50     210      0
..      ...     ...         ...       ...        ...   ...     ...    ...
240      AS      81         SEA       ANC          3   360     219      0
241      B6    1001         BOS       JFK          3   360      71      1
242      B6    1133         SYR       JFK          3   360      85      0
243      B6    1224         RDU       BOS          3   360     101      1
244      B6     155         JFK       MCO          3   360     168      0

[237 rows x 8 columns]

In [18]:
df[df['DayOfWeek'] == 6].head()

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
53799      DL    2344         LAS       CVG          6    10     215      0
53800      CO     269         SFO       IAH          6    15     203      1
53801      US    1558         PHX       CLT          6    15     222      0
53802      AA    2400         LAX       DFW          6    20     165      0
53803      AA    2466         SFO       DFW          6    20     195      0

In [23]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Пример данных
df = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')
minmax_scaler = MinMaxScaler()
df["sepal_length_scaled"] = minmax_scaler.fit_transform(df[["sepal_length_cm"]])

z_scaler = StandardScaler()
df["sepal_width_scaled"] = z_scaler.fit_transform(df[["sepal_width_cm"]])

# Вывод результата
print(df)


     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  sepal_length_scaled  sepal_width_scaled  
0       setosa             0.222222            1.032057  
1      